---
# vars file for consul

consul_url: https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip
consul_download_dir: /root
consul_install_dir: /usr/local/bin
consul_data_dir: /opt/consul
consul_config_dir: /etc/consul.d
consul_pid_file: /var/run/consul.pid
consul_log_file: /var/log/consul.log
#consul_user: "{% if consul_server %}consul{% else %}root{% endif %}"
consul_user: root
#consul_group: "{% if consul_server %}consul{% else %}root{% endif %}"
consul_group: root
consul_service_name: consul
bootstrap_expect: 1
consul_join_tag_key: "target"
consul_join_tag_value: "control_plane"
