---
# handlers file for consul

- name: restart consul
  become: yes
  service:
    name: "{{ consul_service_name }}"
    state: restarted
  tags:
    - consul

- name: reload consul
  become: yes
  service:
    name: "{{ consul_service_name }}"
    state: reloaded
  tags:
    - consul
