---
- name: Install Vault to install dir - copy all files from dir to destination machine
  become: yes
  copy:
    src: "{{ item }}"
    dest: "{{ vault_install_dir }}"
    owner: root
    mode: 0755
  with_fileglob:
    - ./bin/*vault
  tags:
    - vault

- name: Create Vault configuration directory
  become: yes
  file:
    path: "{{ vault_config_dir }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  tags:
    - vault

- name: Create Vault data directory
  become: yes
  file:
    path: "{{ vault_data_dir }}"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: 0755
    state: directory
  tags:
    - vault

- name: Create Vault systemd configuration
  become: yes
  template:
    src: vault.systemd.j2
    dest: /etc/systemd/system/vault.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart vault
  tags:
    - vault
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version|int >= 16

- name: Create Vault configuration file
  become: yes
  template:
    src: vault.hcl.j2
    dest: "{{ vault_config_dir }}/vault.hcl"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart vault
  tags:
    - vault

- name: Create Vault server configuration file
  become: yes
  template:
    src: client.hcl.j2
    dest: "{{ vault_config_dir }}/client.hcl"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart vault
  tags:
    - vault

- name: Ensure Vault service is started and enabled on boot
  become: yes
  service:
    name: "{{ vault_service_name }}"
    state: started
    enabled: yes
  tags:
    - vault

