---
# vars file for vault

vault_url: https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip
vault_download_dir: /root
vault_install_dir: /usr/local/bin
vault_data_dir: /opt/vault
vault_config_dir: /etc/vault.d
vault_pid_file: /var/run/vault.pid
vault_log_file: /var/log/vault.log
#vault_user: "{% if vault_server %}vault{% else %}root{% endif %}"
vault_user: root
#vault_group: "{% if vault_server %}vault{% else %}root{% endif %}"
vault_group: root
vault_service_name: vault
bootstrap_expect: 1
vault_join_tag_key: "target"
vault_join_tag_value: "control_plane"
