---
# tasks file for ansible_filebeat_configured
#- name: install zabbix-agent
#  apt:
#    name: zabbix-agent
#    state: latest
#    update_cache: yes

#- name: ls -l
#  become: yes
#  shell: ls -l 


#- name: ./build-deb.sh
#  become: yes
#  shell: ./build-deb.sh


#- name: apt-get -y install ./build/amazon-efs-utils*deb
#  become: yes
#  shell: apt-get -y install ./build/amazon-efs-utils*deb

- name: mkdir conf
  become: yes
  shell: mkdir -p /mnt/efs/conf

- name: mkdir logs
  become: yes
  shell: mkdir -p /mnt/efs/logs

- name: mkdir datadir
  become: yes
  shell: mkdir -p /mnt/efs/datadir

# name: mount datadir
# become: yes
# shell: mount -t nfs -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport fs-18d9eb40.efs.eu-central-1.amazonaws.com:/ /mnt/efs/datadir


#- name: mount datadir
#  become: yes
#  shell: mount -t efs  fs-18d9eb40:/ /mnt/efs/datadir



- name: mount datadir
  become: yes
  shell: mount -t nfs4 -o lookupcache=positive,nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport 172.16.0.55:/  /mnt/efs/datadir


- name: mount logs
  become: yes
  shell: sudo mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport 172.16.2.152:/ /mnt/efs/logs



- name: mount conf
  become: yes
  shell: sudo mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport 172.16.2.25:/ /mnt/efs/conf


- name: show changes
  become: yes
  shell: df -h



