---
- name: Install Consul to install dir -  copy all files from dir to destination machine
  become: yes
  copy:
    src: "{{ item }}"
    dest: "{{ consul_install_dir }}"
    owner: root
    mode: 0755
  with_fileglob:
    - ./bin/*consul
  tags:
    - consul

- name: Create Consul configuration directory
  become: yes
  file:
    path: "{{ consul_config_dir }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  tags:
    - consul

- name: Create Consul data directory
  become: yes
  file:
    path: "{{ consul_data_dir }}"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0755
    state: directory
  tags:
    - consul

- name: Create Consul systemd configuration
  become: yes
  template:
    src: consul.systemd.j2
    dest: /etc/systemd/system/consul.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart consul
  tags:
    - consul
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version|int >= 16

- name: Create Consul configuration file
  become: yes
  template:
    src: consul.json.j2
    dest: "{{ consul_config_dir }}/consul.json"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart consul
  tags:
    - consul

- name: Create Consul server configuration file
  become: yes
  template:
    src: client.json.j2
    dest: "{{ consul_config_dir }}/client.json"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart consul
  when: consul_server
  tags:
    - consul

- name: Ensure Consul service is started and enabled on boot
  become: yes
  service:
    name: "{{ consul_service_name }}"
    state: started
    enabled: yes
  tags:
    - consul

